---
driver:
  name: dokken
  provision: true
  use_sudo: false
  privileged: true
  pull_chef_image: false
  pull_platform_image: false
  clean_dokken_sandbox: false
  intermediate_instructions:
    - RUN /usr/bin/apt-get update --fix-missing
  use_cache: true
  hostname: ntpdate.example.com

provisioner:
  name: dokken
  deprecations_as_errors: true
  multiple_converge: 2
  enforce_idempotency: true
  client_rb:
    file_atomic_update: false

transport:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
    driver:
      image: dokken/ubuntu-14.04
      pid_one_command: /sbin/init
      cap_add:
        - SYS_ADMIN
  - name: ubuntu-16.04
    driver:
      image: dokken/ubuntu-16.04
      pid_one_command: /bin/systemd
  - name: ubuntu-18.04
    driver:
      image: dokken/ubuntu-18.04
      pid_one_command: /bin/systemd
  - name: ubuntu-20.04
    driver:
      image: dokken/ubuntu-20.04
      pid_one_command: /bin/systemd
  - name: ubuntu-22.04
    driver:
      image: dokken/ubuntu-22.04
      pid_one_command: /bin/systemd

chef18: &chef18 '18.3.0'

suites:
  - name: default-chef13
    driver:
      chef_version: '13'
    verifier: &default_verifier
      inspec_tests:
        - test/integration/default/inspec
      reporter:
        - cli
        - junit:kitchen-reports/%{suite}-%{platform}.xml
    run_list: &default_runlist
      - recipe[ntpdate]

  - name: default-chef14
    driver:
      chef_version: '14'
    verifier:
      <<: *default_verifier
    run_list:
      - *default_runlist

  - name: default-chef15
    driver:
      chef_version: '15'
    verifier:
      <<: *default_verifier
    run_list:
      - *default_runlist

  - name: default-chef16
    driver:
      chef_version: '16'
    verifier:
      <<: *default_verifier
    run_list:
      - *default_runlist

  - name: default-chef17
    driver:
      chef_version: '17.1.35'
    verifier:
      <<: *default_verifier
    run_list:
      - *default_runlist

  - name: default-chef18
    driver:
      chef_version: *chef18
    verifier:
      <<: *default_verifier
    run_list:
      - *default_runlist

  - name: custom-chef13
    driver:
      chef_version: '13'
    verifier: &custom_verifier
      inspec_tests:
        - test/integration/custom/inspec
      reporter:
        - cli
        - junit:kitchen-reports/%{suite}-%{platform}.xml
    run_list:
      - *default_runlist
    attributes: &custom_attributes
      ntpdate:
        enable: true
        ntp_servers:
          - 0.de.pool.ntp.org
          - 1.de.pool.ntp.org
          - 2.de.pool.ntp.org
          - 3.de.pool.ntp.org
        crontab:
          comment: 'This cron syncs the time on Sundays mornings.'
          minute: 0
          hour: 6
          weekday: sun

  - name: custom-chef14
    driver:
      chef_version: '14'
    verifier:
      <<: *custom_verifier
    run_list:
      - *default_runlist
    attributes:
      <<: *custom_attributes

  - name: custom-chef15
    driver:
      chef_version: '15'
    verifier:
      <<: *custom_verifier
    run_list:
      - *default_runlist
    attributes:
      <<: *custom_attributes

  - name: custom-chef16
    driver:
      chef_version: '16'
    verifier:
      <<: *custom_verifier
    run_list:
      - *default_runlist
    attributes:
      <<: *custom_attributes

  - name: custom-chef17
    driver:
      chef_version: '17.1.35'
    verifier:
      <<: *custom_verifier
    run_list:
      - recipe[ntpdate]
    attributes:
      <<: *custom_attributes

  - name: custom-chef18
    driver:
      chef_version: *chef18
    verifier:
      <<: *custom_verifier
    run_list:
      - recipe[ntpdate]
    attributes:
      <<: *custom_attributes

  - name: disabled-chef13
    driver:
      chef_version: '13'
    verifier: &disabled_verifier
      inspec_tests:
        - test/integration/disabled/inspec
      reporter:
        - cli
        - junit:kitchen-reports/%{suite}-%{platform}.xml
    run_list:
      - *default_runlist
    attributes: &disabled_attributes
      ntpdate:
        enable: false
        ntp_servers:
          - server 0.de.pool.ntp.org
          - server 1.de.pool.ntp.org
          - server 2.de.pool.ntp.org
          - server 3.de.pool.ntp.org
        crontab:
          comment: 'This should never appear.'
          minute: 0
          hour: 6
          day: 7

  - name: disabled-chef14
    driver:
      chef_version: '14'
    verifier:
      <<: *disabled_verifier
    run_list:
      - *default_runlist
    attributes:
      <<: *disabled_attributes

  - name: disabled-chef15
    driver:
      chef_version: '15'
    verifier:
      <<: *disabled_verifier
    run_list:
      - *default_runlist
    attributes:
      <<: *disabled_attributes

  - name: disabled-chef16
    driver:
      chef_version: '16'
    verifier:
      <<: *disabled_verifier
    run_list:
      - *default_runlist
    attributes:
      <<: *disabled_attributes

  - name: disabled-chef17
    driver:
      chef_version: '17.1.35'
    verifier:
      <<: *disabled_verifier
    run_list:
      - recipe[ntpdate]
    attributes:
      <<: *disabled_attributes

  - name: disabled-chef18
    driver:
      chef_version: *chef18
    verifier:
      <<: *disabled_verifier
    run_list:
      - recipe[ntpdate]
    attributes:
      <<: *disabled_attributes
