---
driver:
  name: dokken
  provision: true
  use_sudo: false
  privileged: true
  pull_chef_image: false
  pull_platform_image: false
  clean_dokken_sandbox: false
  pid_one_command: /bin/systemd
  intermediate_instructions:
    - RUN /usr/bin/apt-get update --fix-missing
  use_cache: true
  hostname: ntpdate.example.com

provisioner:
  name: dokken
  deprecations_as_errors: true
  multiple_converge: 2
  enforce_idempotency: true
  client_rb:
    file_atomic_update: false

transport:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
    driver:
      image: dokken/ubuntu-18.04
  - name: ubuntu-20.04
    driver:
      image: dokken/ubuntu-20.04
  - name: ubuntu-22.04
    driver:
      image: dokken/ubuntu-22.04
  - name: ubuntu-22.04
    driver:
      image: dokken/ubuntu-22.04


chef17: &chef17 '17.10.0'
chef18: &chef18 '18.4.12'

suites:
  - name: default-chef17
    driver:
      chef_version: *chef17
    verifier: &default_verifier
      inspec_tests:
        - test/integration/default/inspec
      reporter:
        - cli
        - junit:kitchen-reports/%{suite}-%{platform}.xml
    run_list: &default_runlist
      - recipe[ntpdate]

  - name: default-chef18
    driver:
      chef_version: *chef18
    verifier:
      <<: *default_verifier
    run_list:
      - *default_runlist

  - name: custom-chef17
    driver:
      chef_version: *chef17
    verifier: &custom_verifier
      inspec_tests:
        - test/integration/custom/inspec
      reporter:
        - cli
        - junit:kitchen-reports/%{suite}-%{platform}.xml
    run_list:
      - *default_runlist
    attributes: &custom_attributes
      ntpdate:
        enable: true
        ntp_servers:
          - 0.de.pool.ntp.org
          - 1.de.pool.ntp.org
          - 2.de.pool.ntp.org
          - 3.de.pool.ntp.org
        crontab:
          comment: 'This cron syncs the time on Sundays mornings.'
          minute: 0
          hour: 6
          weekday: sun

  - name: custom-chef18
    driver:
      chef_version: *chef18
    verifier:
      <<: *custom_verifier
    run_list:
      - *default_runlist
    attributes:
      <<: *custom_attributes

  - name: disabled-chef17
    driver:
      chef_version: *chef17
    verifier: &disabled_verifier
      inspec_tests:
        - test/integration/disabled/inspec
      reporter:
        - cli
        - junit:kitchen-reports/%{suite}-%{platform}.xml
    run_list:
      - *default_runlist
    attributes: &disabled_attributes
      ntpdate:
        enable: false
        ntp_servers:
          - server 0.de.pool.ntp.org
          - server 1.de.pool.ntp.org
          - server 2.de.pool.ntp.org
          - server 3.de.pool.ntp.org
        crontab:
          comment: 'This should never appear.'
          minute: 0
          hour: 6
          day: 7

  - name: disabled-chef18
    driver:
      chef_version: *chef18
    verifier:
      <<: *disabled_verifier
    run_list:
      - *default_runlist
    attributes:
      <<: *disabled_attributes
